In [3]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [4]:
import tensorflow as tf

In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.2760001 ,  0.20051023,  0.21066606,  0.23892564, -0.01546118,
         0.05086167,  0.9234203 , -0.5714477 , -0.17644179, -0.44190437]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.11317104, 0.10494228, 0.10601348, 0.1090521 , 0.08455811,
        0.09035639, 0.2162252 , 0.0484946 , 0.07198505, 0.05520181]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.4039934

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2850 - accuracy: 0.9177
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1363 - accuracy: 0.9594
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1049 - accuracy: 0.9687
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0854 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0739 - accuracy: 0.9771


In [14]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0786 - accuracy: 0.9770


[0.07856099307537079, 0.9769999980926514]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.6889959e-08, 1.2667336e-08, 4.6766818e-05, 1.4766752e-03,
        2.4270479e-12, 2.4816876e-07, 6.1641995e-13, 9.9845552e-01,
        2.3145876e-06, 1.8409706e-05],
       [6.4034900e-08, 2.5216723e-06, 9.9997663e-01, 1.1889536e-07,
        1.8990415e-15, 4.1991453e-07, 2.0346884e-06, 7.4938267e-15,
        1.8093366e-05, 6.4509745e-14],
       [1.7101371e-06, 9.9616915e-01, 3.8421914e-04, 6.5192442e-05,
        2.9221349e-04, 2.1181031e-04, 5.7550675e-05, 1.7884974e-03,
        1.0275503e-03, 1.9782676e-06],
       [9.9994755e-01, 1.3104395e-10, 1.8326147e-05, 7.3153558e-08,
        4.3779323e-08, 2.4048670e-06, 7.1099566e-06, 1.5098848e-05,
        5.0544935e-07, 8.8229435e-06],
       [7.8266226e-08, 2.3151332e-09, 1.4651637e-05, 2.5273600e-08,
        9.9468696e-01, 2.1319254e-06, 2.0516061e-06, 5.7679230e-05,
        2.2071226e-06, 5.2342839e-03]], dtype=float32)>